version: "3.7"
services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
