version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: postgres
      PG_USER: postgres
      PG_PASS: postgres
      SEEDS_ENABLED: 'true'
    ports:
      - 4000:4000
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
