version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-postgres-objection
    restart: always
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABASE: postgres
      PG_USER: postgres
      PG_PASS: postgres
    ports:
      - 4000:4000
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
